//package com.example.microservice;
///*
// * Api Documentation
// * Api Documentation
// *
// * OpenAPI spec version: 1.0
// *
// *
// * NOTE: This class is auto generated by the swagger code generator program.
// * https://github.com/swagger-api/swagger-codegen.git
// * Do not edit the class manually.
// */
//
//
//import io.swagger.client.ApiException;
//import io.swagger.client.model.Customer;
//import io.swagger.client.model.Order;
//import org.junit.Test;
//import org.junit.Ignore;
//
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
///**
// * API tests for ControllerApi
// */
//@Ignore
//public class ControllerApiTest {
//
//    private final ControllerApi api = new ControllerApi();
//
//
//    /**
//     * deleteAllCustomers
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void deleteAllCustomersUsingDELETETest() throws ApiException {
//        api.deleteAllCustomersUsingDELETE();
//
//        // TODO: test validations
//    }
//
//    /**
//     * deleteAllOrders
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void deleteAllOrdersUsingDELETETest() throws ApiException {
//        api.deleteAllOrdersUsingDELETE();
//
//        // TODO: test validations
//    }
//
//    /**
//     * getAllCustomers
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void getAllCustomersUsingGETTest() throws ApiException {
//        List<Customer> response = api.getAllCustomersUsingGET();
//
//        // TODO: test validations
//    }
//
//    /**
//     * getAllOrders
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void getAllOrdersUsingGETTest() throws ApiException {
//        List<Order> response = api.getAllOrdersUsingGET();
//
//        // TODO: test validations
//    }
//
//    /**
//     * placeOrder
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void placeOrderUsingPOSTTest() throws ApiException {
//        Order order = null;
//        api.placeOrderUsingPOST(order);
//
//        // TODO: test validations
//    }
//
//    /**
//     * saveCustomer
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void saveCustomerUsingPOSTTest() throws ApiException {
//        Customer customer = null;
//        api.saveCustomerUsingPOST(customer);
//
//        // TODO: test validations
//    }
//
//}
